spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.url=jdbc:postgresql://localhost:5432/NoRe
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuração de Email
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=hartmanngabriel17@gmail.com
spring.mail.password=mrkn dwwa igaz lehp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# URL do frontend para links de verificação
app.frontend.url=https://nore.loca.lt